version: "3"
services:
    vision:
        image: vision
        build:
            context: .
            dockerfile: ./Dockerfile
        networks:
            - back
        container_name: grievance
        restart: on-failure
        volumes:
            - ./src:/dult-ai/src/src/
        environment:
          - CMD_TO_EXECUTE=run_grievance_worker
        depends_on:
          - localstack
networks:
    back:





